#!/bin/bash -p
# Copyright (C) 2021 Henryws
#
# This file is part of Wiz
#
# Wiz is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License
#
# Wiz is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Wiz. If not, see <https://www.gnu.org/licenses/>.

set -e
shopt -s nullglob
stty -echoctl

NC='\033[0m'       				# Text Reset
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan


cleanup() {
	if test -f /tmp/WIZ_TMP_FILE; then
		rm -f /tmp/WIZ_TMP_FILE
	fi
	echo -e "${NC}"
	exit
}

trap cleanup SIGINT

prompt() {
	unset OPTION
	if [[ -n "$1" ]]; then
		echo -ne "${1}: ${BICyan}"
	else
		echo -ne "Enter an option: ${BICyan}"
	fi
	read -r OPTION
	echo -ne "${NC}"
}

main_menu() {
	echo -e "${BIGreen}$1${NC}"
	echo -e "${BIPurple}1${NC}) View previous Wiz's"
	echo -e "${BIPurple}2${NC}) Write a new Wiz"
	echo -e "${BIPurple}3${NC}) Delete Wiz's"
	echo -e "${BIPurple}4${NC}) Get info on a Wiz"
	echo -e "${BIRed}0${NC}) Exit"
}

main_menu "Main Menu"
prompt

case "${OPTION}" in
	0)
		exit
		;;
	1)
		cd "${HOME}/.local/share/wiz"
		for i in *; do
			files+=("$i")
		done
		PS3="
Select a Wiz to read, or $(tput setaf 1)0$(tput sgr0) to exit: "
		echo
		select file in "${files[@]}"; do
			if [[ $REPLY == "0" ]]; then
				exit
			elif [[ -z $file ]]; then
				echo 'Invalid choice, try again' >&2
			else
				break
			fi
		done
		if [[ "$(tput lines)" < "$(wc -l "$file")" ]]; then
			less -R "$file"
		else
			printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
			echo -e "\n"
			cat "$file"
			echo
			printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
		fi
		;;
	2)
		prompt "What shall this Wiz be called"
		export WIZ_FILE="${OPTION}"
		if test -f "${HOME}/.local/share/wiz/${OPTION}"; then
			echo -e "${BIRed}Wiz already exists${NC}"
			exit 1
		fi
		rm -f /tmp/WIZ_TMP_FILE &>/dev/null || true
		"${EDITOR}" "/tmp/WIZ_TMP_FILE"
		if ! [[ -s "/tmp/WIZ_TMP_FILE" ]]; then
			echo -e "${BIRed}File empty${NC}"
			exit 1
		fi
		mkdir -p "${HOME}/.local/share/wiz"
		tee "${HOME}/.local/share/wiz/${WIZ_FILE}" >/dev/null < /tmp/WIZ_TMP_FILE
		echo -e "${BICyan}Saved ${NC}${OPTION}"
		exit
		;;
	3)
		cd "${HOME}/.local/share/wiz"
		for i in *; do
			files+=("$i")
		done
		PS3="
Select a Wiz to delete, or $(tput setaf 1)0$(tput sgr0) to exit: "
		echo
		select file in "${files[@]}"; do
			if [[ $REPLY == "0" ]]; then
				exit
			elif [[ -z $file ]]; then
				echo 'Invalid choice, try again' >&2
			else
				break
			fi
		done
		rm -I "${file[@]:?}"
		echo -e "Deleted ${BICyan}$file${NC}"
		;;
	4)
		cd "${HOME}/.local/share/wiz"
		echo -e "\nfile : permission : size"
		stat -c '%n : %U : %s' -- *
		;;
	*)
		echo -e "${BIRed}Invalid option given${NC}"
		exit 1
esac
